name: yesh_dibur_frontend_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  dio: ^5.10.0
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
